os: linux
dist: focal
language: shell

branches:
  except:
    - /^deploy-.*$/

git:
  depth: false

before_install:
  - sudo apt-get -qq update
  - cp assets/mycv.cls gr
  - cp assets/mycv.cls eng
  - sudo apt-get install --no-install-recommends -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-fonts-extra-links texlive-font-utils texlive-plain-generic texlive-xetex texlive-lang-greek lmodern ghostscript

script:
  - bash publish.sh gr cv
  - bash publish.sh eng cv

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "ChrisKar96"
  - git config --local user.email "me@christoskaramo.tk"
  - export TRAVIS_TAG=${TRAVIS_TAG:-"deploy-"$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  skip_cleanup: true
  file:
  - ./gr/cv-gr.pdf
  - ./eng/cv-eng.pdf
  on:
    repo: ChrisKar96/CV-LaTeX