---
sudo: require
dist: xenial
language: bash

before_install:
  - sudo apt-get -qq update
  - sudo mkdir /home/travis/texmf
  - cp assets/mycv.cls /home/travis/texmf
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-xetex texlive-lang-greek ghostscript

script:
  - bash publish.sh ./gr/ cv
  - bash publish.sh ./eng/ cv

deploy:
  provider: releases
  github-token: $GITHUB_TOKEN
    file: 
  - ./gr/cv-gr.pdf
  - ./eng/cv-eng.pdf
  skip_cleanup: true
  on:
    repo: ChrisKar96/CV-LaTeX